const data = [
  {
    discordName: 'gamingvyce',
    discordDiscriminator: '8526',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Togashi Komhl',
    discordDiscriminator: '7296',
    clanId: 3,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'zorzo',
    discordDiscriminator: '8381',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Joe From Cincinnati',
    discordDiscriminator: '7070',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'RhialtoTheMarvellous',
    discordDiscriminator: '3444',
    clanId: 5,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Hos',
    discordDiscriminator: '6694',
    clanId: 7,
    timezoneId: 7,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'mechmisfit',
    discordDiscriminator: '6894',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Mind’s Desire',
    discordDiscriminator: '1911',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'madavaster',
    discordDiscriminator: '3690',
    clanId: 6,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Jmart',
    discordDiscriminator: '6576',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Demagogue',
    discordDiscriminator: '8792',
    clanId: 5,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Masashigi',
    discordDiscriminator: '2671',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Hamertron',
    discordDiscriminator: '8912',
    clanId: 2,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'midorikage',
    discordDiscriminator: '1254',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'shoking',
    discordDiscriminator: '2017',
    clanId: 7,
    timezoneId: 4,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'MarcusBatty',
    discordDiscriminator: '0125',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Fyeya',
    discordDiscriminator: '0454',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'bitmetal',
    discordDiscriminator: '3377',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'kibosh',
    discordDiscriminator: '3902',
    clanId: 7,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'arash_suri',
    discordDiscriminator: '3491',
    clanId: 3,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Doji Hoturi the Heartless',
    discordDiscriminator: '9632',
    clanId: 2,
    timezoneId: 5,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Grabba01',
    discordDiscriminator: '7957',
    clanId: 3,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Randthemad',
    discordDiscriminator: '0259',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Brood',
    discordDiscriminator: '3278',
    clanId: 4,
    timezoneId: 6,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Sparktitan',
    discordDiscriminator: '8764',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Das_Boom',
    discordDiscriminator: '5482',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Skyeleis',
    discordDiscriminator: '6669',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'IkomaQuant',
    discordDiscriminator: '9533 ',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Droog',
    discordDiscriminator: '9692',
    clanId: 3,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'MaverickMartell',
    discordDiscriminator: '3502',
    clanId: 4,
    timezoneId: 5,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Llamaman',
    discordDiscriminator: '4768',
    clanId: 7,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Isomalt',
    discordDiscriminator: '7830',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Woldie',
    discordDiscriminator: '4823',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Kaza',
    discordDiscriminator: '6609',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'coyote',
    discordDiscriminator: '6029',
    clanId: 5,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Flygare',
    discordDiscriminator: '0784',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Bill_Kirlisarmy',
    discordDiscriminator: '1737',
    clanId: 5,
    timezoneId: 5,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Lono',
    discordDiscriminator: '4368',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'zarepath',
    discordDiscriminator: '0186',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'sla-dreamer',
    discordDiscriminator: '0038',
    clanId: 5,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'KailamPD',
    discordDiscriminator: '1447',
    clanId: 5,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Bill_Kirlisarmy',
    discordDiscriminator: '1737',
    clanId: 1,
    timezoneId: 5,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'gamingvyce',
    discordDiscriminator: '8526',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Suburbaknght',
    discordDiscriminator: '4584',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'foxhound',
    discordDiscriminator: '8176',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'harandil',
    discordDiscriminator: '1699',
    clanId: 6,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Luis "Auran" Acosta',
    discordDiscriminator: '3591',
    clanId: 3,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'qkieu',
    discordDiscriminator: '1486',
    clanId: 3,
    timezoneId: 5,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'pimittens',
    discordDiscriminator: '9959',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'AkodoGinawa',
    discordDiscriminator: '1132',
    clanId: 4,
    timezoneId: 1,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Hamoun',
    discordDiscriminator: '9268',
    clanId: 3,
    timezoneId: 7,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Kakita Leniel',
    discordDiscriminator: '7974',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Whiteblade111',
    discordDiscriminator: '5606',
    clanId: 7,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'LingeringDrama',
    discordDiscriminator: '4082',
    clanId: 7,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'UnderDarkLord',
    discordDiscriminator: '0667',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Neph',
    discordDiscriminator: '7320',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'IsawaPain',
    discordDiscriminator: '9339',
    clanId: 7,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Daidoji lag0s',
    discordDiscriminator: '6429',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Darklordjim',
    discordDiscriminator: '7809',
    clanId: 5,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'JustDave',
    discordDiscriminator: '5224',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Code Baboon',
    discordDiscriminator: '9211',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Gnimsh',
    discordDiscriminator: '4384',
    clanId: 2,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Jokingly',
    discordDiscriminator: '7504',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Daidoji_Micah',
    discordDiscriminator: '1184',
    clanId: 2,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'EvanEGibbs',
    discordDiscriminator: '7560',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'gamingvyce',
    discordDiscriminator: '8526',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Akodo_Grimardi',
    discordDiscriminator: '1624',
    clanId: 4,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'swartzkoff',
    discordDiscriminator: '7482',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'ZELOisBack',
    discordDiscriminator: '2201',
    clanId: 1,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Kaito Kikaze',
    discordDiscriminator: '2318',
    clanId: 5,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'D4rkWolf10',
    discordDiscriminator: '2781',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Shu Guangtou',
    discordDiscriminator: '9646',
    clanId: 7,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'jairoe03',
    discordDiscriminator: '9086',
    clanId: 6,
    timezoneId: 3,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Kakita Akira',
    discordDiscriminator: '4128',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Hos',
    discordDiscriminator: '6694',
    clanId: 7,
    timezoneId: 7,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'uzix',
    discordDiscriminator: '5983 ',
    clanId: 5,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'gerbo78',
    discordDiscriminator: '4696',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'garrinski',
    discordDiscriminator: '3408',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'garrinski',
    discordDiscriminator: '3408',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'LGB',
    discordDiscriminator: '7643',
    clanId: 6,
    timezoneId: 3,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'sargent212',
    discordDiscriminator: '9283',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'White Liger',
    discordDiscriminator: '8403',
    clanId: 6,
    timezoneId: 6,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Jamie',
    discordDiscriminator: '5308',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'UTasteSoSo',
    discordDiscriminator: '3974',
    clanId: 7,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'akodod',
    discordDiscriminator: '8226',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Maka',
    discordDiscriminator: '8016',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Agram',
    discordDiscriminator: '2109 ',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Toric',
    discordDiscriminator: '0927',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'mythicFOX',
    discordDiscriminator: '5743',
    clanId: 1,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'GrengisKhan',
    discordDiscriminator: '6802',
    clanId: 7,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Erik',
    discordDiscriminator: '2965',
    clanId: 2,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'TLFJ',
    discordDiscriminator: '7286',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Djinncito',
    discordDiscriminator: '4373',
    clanId: 2,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Matrix30815',
    discordDiscriminator: '8010',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'MechMage',
    discordDiscriminator: '2563',
    clanId: 6,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Humblestmonk',
    discordDiscriminator: '8827',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Coyotte',
    discordDiscriminator: '5159',
    clanId: 1,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'DanVan',
    discordDiscriminator: '4519',
    clanId: 1,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Mirumoto Kai',
    discordDiscriminator: '6874',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Baron Fel',
    discordDiscriminator: '7046',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'LaMoj',
    discordDiscriminator: '6748',
    clanId: 5,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Jamesy',
    discordDiscriminator: '3975',
    clanId: 2,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Xupim',
    discordDiscriminator: '9124',
    clanId: 6,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'zorzo',
    discordDiscriminator: '8381',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'CuzinVin8',
    discordDiscriminator: '0777',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Damabiah',
    discordDiscriminator: '1548',
    clanId: 1,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Nivek',
    discordDiscriminator: '3686',
    clanId: 6,
    timezoneId: 6,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Schrodes',
    discordDiscriminator: '8145',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'AmmanasPL',
    discordDiscriminator: '2703',
    clanId: 6,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'espie',
    discordDiscriminator: '0253',
    clanId: 2,
    timezoneId: 1,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Akai',
    discordDiscriminator: '5121',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Wharrison1315',
    discordDiscriminator: '2991 ',
    clanId: 4,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Ide Leenath',
    discordDiscriminator: '9606',
    clanId: 7,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'leventei88',
    discordDiscriminator: '6008',
    clanId: 1,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'action_johnny',
    discordDiscriminator: '0591',
    clanId: 7,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Kakita Koji',
    discordDiscriminator: '8860',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'SirLargeness',
    discordDiscriminator: '1019',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'alphasquid',
    discordDiscriminator: '2157',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Toturi Mizu (Yvonne)',
    discordDiscriminator: '4254',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'bienias',
    discordDiscriminator: '7581',
    clanId: 2,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Heirgunther',
    discordDiscriminator: '3196',
    clanId: 6,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Miniindahouse',
    discordDiscriminator: '7492',
    clanId: 1,
    timezoneId: 7,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'cobaltblue',
    discordDiscriminator: '8729',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'PeterSaloom',
    discordDiscriminator: '0171',
    clanId: 6,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Handsome_Dan',
    discordDiscriminator: '8310',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'padula',
    discordDiscriminator: '8419',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'doji_odi',
    discordDiscriminator: '7358',
    clanId: 2,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'szuturon',
    discordDiscriminator: '2345',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'AJ Moore',
    discordDiscriminator: '0548',
    clanId: 5,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Sintor',
    discordDiscriminator: '1456',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Lambershaspy',
    discordDiscriminator: '6015',
    clanId: 3,
    timezoneId: 1,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Seth',
    discordDiscriminator: '0029',
    clanId: 3,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Gulbrandr',
    discordDiscriminator: '4446',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'sruman',
    discordDiscriminator: '7696',
    clanId: 3,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Chaley',
    discordDiscriminator: '2202',
    clanId: 3,
    timezoneId: 1,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'PhoenixFox',
    discordDiscriminator: '3255',
    clanId: 3,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'nightcrawlers',
    discordDiscriminator: '274&',
    clanId: 3,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Jeremey',
    discordDiscriminator: '2822',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'VoidCircuit',
    discordDiscriminator: '2131',
    clanId: 5,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'acecase',
    discordDiscriminator: '3167',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Chuterêve',
    discordDiscriminator: '7708',
    clanId: 2,
    timezoneId: 4,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'InsaneManiac',
    discordDiscriminator: '4364',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'IkomaQuant',
    discordDiscriminator: '9533',
    clanId: 4,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Tattooedcrab',
    discordDiscriminator: '',
    clanId: 1,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'B3ardofZ3us',
    discordDiscriminator: '2407',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Finster27',
    discordDiscriminator: '6429',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'RawrenLauren',
    discordDiscriminator: '1810',
    clanId: 7,
    timezoneId: 5,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Yamaneko',
    discordDiscriminator: '0193',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Enegon',
    discordDiscriminator: '8434',
    clanId: 7,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Ikoma Eto',
    discordDiscriminator: '7023',
    clanId: 4,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Tenerim',
    discordDiscriminator: '1298',
    clanId: 4,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Awakan',
    discordDiscriminator: '6929',
    clanId: 5,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Wobberjacky',
    discordDiscriminator: '5648',
    clanId: 1,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Will',
    discordDiscriminator: '6831',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Apryl2007',
    discordDiscriminator: '2147',
    clanId: 3,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Darthnazrael',
    discordDiscriminator: '5029',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'Mercer',
    discordDiscriminator: '8575',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Redorick',
    discordDiscriminator: '2078',
    clanId: 7,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Pogona barbata',
    discordDiscriminator: '9917',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'IsawaPain',
    discordDiscriminator: '9339',
    clanId: 5,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Chon_Wang',
    discordDiscriminator: '5939',
    clanId: 2,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Koppie2k',
    discordDiscriminator: '4676',
    clanId: 4,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Tokeru',
    discordDiscriminator: '2221',
    clanId: 6,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Steelfur',
    discordDiscriminator: '4075',
    clanId: 3,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Infinight',
    discordDiscriminator: '7632',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Merlin',
    discordDiscriminator: '5091',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Syrail',
    discordDiscriminator: '1580',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'SorrykidO',
    discordDiscriminator: '0190',
    clanId: 2,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Turco',
    discordDiscriminator: '1527',
    clanId: 3,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Daxora',
    discordDiscriminator: '6188',
    clanId: 5,
    timezoneId: 5,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Draz999',
    discordDiscriminator: '0076',
    clanId: 1,
    timezoneId: 3,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Haydog',
    discordDiscriminator: '9483',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'neutral',
  },
  {
    discordName: 'nerdydude777',
    discordDiscriminator: '7508',
    clanId: 5,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'sandybell',
    discordDiscriminator: '2298',
    clanId: 5,
    timezoneId: 4,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'Das_Boom',
    discordDiscriminator: '5482',
    clanId: 6,
    timezoneId: 2,
    timezonePreferenceId: 'similar',
  },
  {
    discordName: 'SamuraiYan',
    discordDiscriminator: '3021',
    clanId: 2,
    timezoneId: 3,
    timezonePreferenceId: 'neutral',
  },
]

exports.seed = function(knex) {
  return knex('tournaments')
    .insert(
      {
        name: 'Season 10',
        description: 'Seed data',
        startDate: new Date('2018-09-01'),
        statusId: 'upcoming',
        typeId: 'monthly',
      },
      '*'
    )
    .then(({ id: tournamentId }) =>
      Promise.all(
        data.map(row => {
          knex('users')
            .insert(
              {
                discordId: `${row.discordName}#${row.discordDiscriminator}`,
                permissions: 0,
                discordName: row.discordName,
                discordDiscriminator: parseInt(row.discordDiscriminator, 10),
              },
              '*'
            )
            .then(user =>
              knex('participants').insert({
                userId: user.discordId,
                clanId: row.clanId,
                tournamentId,
                timezoneId: row.timezoneId,
                timezonePreferenceId: row.timezonePreferenceId,
              })
            )
        })
      )
    )
}
