name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn test
   
  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: discord-league
          heroku_email: luiz@socrate.com.br
          healthcheck: https://discord-league.herokuapp.com/api/ping
          rollbackonhealthcheckfailed: true
